app/__init__.py
from flask import Flask, render_template
from config import Config
from .site.routes import site
from .authentication.routes import auth

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
# from helpers import JSONEncoder

from .site.routes import search

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
# app.register_blueprint(api)

# app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

#apparently doing this will allow me to call a function in jinja2
app.jinja_env.globals.update(search=search)

app/authentication/routes.py
from forms import UserLoginForm, UserCreationForm, EditProfileForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import check_password_hash
from flask_login import UserMixin, login_user
from flask_login import LoginManager

# imports for flask login 
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserCreationForm()
    if request.method == "POST":
        print("POST request made.")
        if form.validate():
            username = form.username.data
            email = form.email.data
            password = form.password.data

            user = User(username, email, password)

            db.session.add(user)
            db.session.commit()
            print(f'A User has been added to the database.\nEmail: {email}\nUsername: {username}\nPassword: {password}')
            flash('Account registered.', 'success')
            return redirect(url_for('auth.signin'))
        else:
            flash('Validation failed. Please try again.', 'error')
    return render_template('sign_up.html', form=form)



@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            print(f'A user tried to login.\nUsername: {username}\nPassword: {password}')

            user = User.query.filter(User.username == username).first()
            print(f'User.username from DB: {user.username}\nUsername from form: {username}')
            
            if user:
                print(check_password_hash(user.password, password))
                # if check_password_hash(user.password, password):
                login_user(user)
                print(f'{username} has logged in!')
                return redirect(url_for('site.home'))

            else:
                print('You do not have access to this content.', '\nauth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check your Form')
    return render_template('sign_in.html', form=form, current_user=current_user)



@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required, current_user
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
from bs4 import BeautifulSoup
import json
import re
from bs4 import BeautifulSoup
from jinja2 import Environment
from models import User, SavedRecipes, db

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/about')
def about():
    return render_template('about.html')

@site.route('/profile')
@login_required
def profile():
    if current_user:
        retrieved = db.session.query(SavedRecipes).all()
        print(retrieved)


    return render_template('profile.html', data=retrieved)



@site.route('/search', methods = ["GET", "POST"])
def search():
    url = "https://api.spoonacular.com/recipes/complexSearch?"
    #Grabbing the input from the HTML form
    item = request.form.get('inputsearch')
    print(f"A user searched for: {item}")

    parameters = {
        'query' :{item},
        'number' : 10,
        'apiKey' : '07607f40a346438790c194f4913ce4a3'
    }

    headers = {
        'Content-Type' : 'application/json'
    }
    session = Session()
    session.headers.update(headers)
   
    try:
        response = session.get(url, params=parameters)
        data = json.loads(response.text)
        print(data['results'])

        for food in data['results']:
            print(food)
            food = {
                'title':food['title'],
                'id': food['id'],
                'image': food['image']
            }
            #Hoping to make this a global variable so I may access this in another function.
            global varid
            varid= food['id']
            global vartitle
            vartitle = food['title']
            global varimage
            varimage = food['image']

    except (ConnectionError, Timeout, TooManyRedirects) as error:
        print(error)

    return render_template('search.html', dict=dict, item=item, data=data, food=food, id=id)



@site.route('/recipe', methods = ["GET", "POST"])
def recipeinfo():
    # global id
    # global id only grabs the last item from the query, not the corresponding so:
    id = request.args.get('id')
    print(f"Recipe ID: {id}")
    #For the summary, but we need the actaul recipe steps
    # url = f'https://api.spoonacular.com/recipes/{id}/summary?'
    url=f'https://api.spoonacular.com/recipes/{id}/information?'

    parameters = {
        'apiKey' : '07607f40a346438790c194f4913ce4a3'
    }

    headers = {
        'Content-Type' : 'application/json'
    }
    session = Session()
    session.headers.update(headers)
    # dont need this anymore
    # print(url)

    try:
        response = session.get(url, params=parameters)
        data = json.loads(response.text)
        # print(response)
        # print(data)

        # create an empty array to store the ingredients
        ingredients = []
        for ingredient in data['extendedIngredients']:
            # access the value of the 'original' field for each ingredient
            original = ingredient['original']
            ingredients.append(original)
            print(original)
        # ITS SOUP TIME
        # Cleaning data'instructions' since the response includes html tags that I do not want
        soup = BeautifulSoup(data['instructions'], 'html.parser')
        # extract the instructions text from the parsed data
        instructions = soup.get_text()
        newinstructions = instructions.replace(re.escape('.'), '.\n')

        recipeitems={}
        recipeitems={
            'title': data['title'],
            'preptime': data['preparationMinutes'],
            'cooktime':data['cookingMinutes'],
            'servings':data['servings'],
            'image':data['image'],
            'instructions': newinstructions
        }
        print(recipeitems)

        global varprep 
        varprep = recipeitems['preptime']
        global vartime
        vartime = recipeitems['cooktime']
        global varservings
        varservings = recipeitems['servings']

    except (ConnectionError, Timeout, TooManyRedirects) as error:
        print(error)

    return render_template('recipe.html', recipeitems=recipeitems, ingredients=ingredients)



@site.route('/recipe/save', methods=["GET", "POST"])
@login_required
def save_recipe():
    #import global variables of title and id into this function
    varid
    print(varid)
    vartitle
    print(vartitle)
    varimage
    print(varimage)
    varprep
    vartime
    varservings

    recipe = SavedRecipes(rid=varid,title=vartitle, img_url=varimage, user_id=current_user.id, preptime=varprep, cooktime=vartime, servings=varservings)
    db.session.add(recipe)
    db.session.commit()
    print('Recipe added successfully')
    return render_template('profile.html')



@site.route('/recipe/<int:recipe_id>/delete', methods=['DELETE','GET', 'POST'])
@login_required
def delete_recipe(recipe_id):
    if current_user:
        recipe = SavedRecipes.query.filter_by(rid = recipe_id).first()
        print(recipe)
        db.session.delete(recipe)
        db.session.commit()


    return render_template('profile.html')

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <title>crispi - restaurant recipes</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS v5.2.0-beta1 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <script src="https://cdn.lordicon.com/qjzruarw.js"></script>
    <script src="https://kit.fontawesome.com/b62c5ddde3.js" crossorigin="anonymous"></script>
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles/main.css') }}">
    <link rel="shortcut icon" href="/app/static/images/favicon_io (1)/apple-touch-icon.png" type="image/x-icon">

</head>

<body>
  <header>
    <nav class=" navbar navbar-expand-lg bg-light">
        <div class="container-fluid d-flex justify-content-center">
          <lord-icon
          src="https://cdn.lordicon.com/zkazkzgr.json"
          trigger="hover"
          style="width:75px;height:75px">
          </lord-icon>
          <a class="navbar-brand animate__animated animate__tada" href="{{ url_for('site.home') }}">crispi</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0" id="navbarlist">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('site.home') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('site.about') }}">About</a>
              </li>
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('site.profile') }}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('auth.logout') }}">Sign-Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('auth.signin') }}">Sign-in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('auth.signup') }}">Sign-Up</a>
              </li>
            </ul>
            {% endif %}
            {% if current_user.is_authenticated %}
            <span class="navbar-text">
              Welcome, {{ current_user.username.title() }}!
            </span>
            {% endif %}
          </div>
        </div>
      </nav>
  </header>

  <main>
    <!--magic jinja stuff-->
    {% block content %}



    {% endblock %}
  </main>

  <footer>
    
    <!-- place footer here -->
    <div class="container-fluid" id="realfooter">
      <div class="container text-center">
        <div class="row">
          <div class="col">
          </div>
          <div class="col-6">
            <div class="row">
              <h4>crispi, a resturant recipe app</h4>
            </div>
            <div class="row">
              <p>Thanks for coming. I don't really know what to put here. Anyways...</p>
            </div>
            <div class="flex-row d-inline-flex pb-3">
              <a id="poop" href="https://github.com/albeoanguis1"><i class="fa-brands fa-github fa-xl p-2"></i></a>
              <a id="poop" href="https://www.linkedin.com/in/antoniopopoca001/"><i class="fa-brands fa-linkedin fa-xl p-2"></i></a>
            </div>
          </div>
          <div class="col">
          </div>
        </div>
      </div>
    </div>
    <div class="custom-shape-divider-bottom-1671068767" id="footerpoop">
      <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
          <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
          <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fill"></path>
          <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fill"></path>
      </svg>
  </div>
  </footer>

  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
    integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous">
  </script>
</body>

</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'Stick your email here!') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Type ya password, kid.") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2", placeholder="Submit")}}

</form>